config/routes.rb
Rails.application.routes.draw do
  
  root "liverpool#index"
  get '/liverpool/index'=>'liverpool#index'
  get '/liverpool/new'=>'liverpool#new' 
  
  post '/liverpool/create' => 'liverpool#create' , as: 'liverpool_create'
  
  
  get '/liverpool/destroy/:list_id' => 'liverpool#destroy'
  
  get '/liverpool/edit/:list_id' => 'liverpool#edit' , as: 'liverpool_edit'
  
  
  post '/liverpool/update/:list_id' =>'liverpool#update'
  
  
  get '/liverpool/guest_new'=>'liverpool#guest_new'
  
  post '/liverpool/guest_create' => 'liverpool#guest_create'
  
  
  get '/liverpool/guest_destroy/:guest_id' => 'liverpool#guest_destroy'
  
  get '/liverpool/guest_edit/:guest_id' => 'liverpool#guest_edit'
  
  
  
  
  
  post '/liverpool/guest_update/:guest_id' =>'liverpool#guest_update'
  
  

end

app/models/guest.rb
class Guest < ActiveRecord::Base
end

app/models/list.rb
class List < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/liverpool_controller.rb
class LiverpoolController < ApplicationController
  
    def index
        @lists=List.all
        @guests=Guest.all
    end
    
    def new
        @list= List.new
    end
    
    def create
        @list=List.new
        @list.name=params[:list][:name]
        @list.year_birth=params[:list][:year_birth]
        @list.height=params[:list][:height]
        @list.weight=params[:list][:weight]
        @list.position=params[:list][:position]
        @list.save
        
        redirect_to "/liverpool/index"
    end
    
    # def new
    # end
    
    # def create
    #     @list=List.new
    #     @list.name=params[:input_name]
    #     @list.year_birth=params[:input_year_birth]
    #     @list.height=params[:input_height]
    #     @list.weight=params[:input_weight]
    #     @list.position=params[:input_position]
    #     @list.save
        
    #     redirect_to "/liverpool/index"
    # end
    
    def destroy
        list = List.find(params[:list_id])
        list.destroy
        
        redirect_to '/liverpool/index'
    end
    
    def edit
        @list = List.find(params[:list_id])
    end
    
    def update
        list = List.find(params[:list_id])
        list.name=params[:name]
        list.year_birth=params[:year_birth]
        list.height=params[:height]
        list.weight=params[:weight]
        list.position=params[:position]
    
        list.save
        
        redirect_to '/liverpool/index'
    end
    
    def guest_new
    end
    
    def guest_create
        @guest=Guest.new
        @guest.content=params[:guest_content]
        
        @guest.save
        
        redirect_to "/liverpool/index"
    end
    
    def guest_destroy
        guest = Guest.find(params[:guest_id])
        guest.destroy
        
        redirect_to '/liverpool/index'
    
    end
    
    def guest_edit
        @guest = Guest.find(params[:guest_id])
    end
    
    def guest_update
        guest = Guest.find(params[:guest_id])
        guest.content=params[:guest_content]
        
        guest.save
          
        redirect_to "/liverpool/index"
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/liverpool_helper.rb
module LiverpoolHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/liverpool/edit.html.erb
<p> Edit Player Profile</p>




<form action='/liverpool/update/<%=@list.id%>' method='post'>
    Name: <input type="text" name="name" value='<%=@list.name%>'></input><br>
    Year of Birth: <input type="text" name="year_birth" value='<%=@list.year_birth%>'></input><br>
    Height: <input type="text" name="height" value='<%=@list.height%>'></input><br>
    Weight: <input type="text" name="weight" value='<%=@list.weight%>'></input><br>
    Position: <input type="text" name="position" value='<%=@list.position%>'></input><br><br>
    <input type="submit" value="edit"></input>
    
</form>

app/views/liverpool/guestbook_edit.html.erb
<form action='/liverpool/guest_update/<%=@guest.id%>' method='post'>
<%= <%= hidden_field_tag hidden_field_tag hidden_field_tag :authenticity_token authenticity_token authenticity_token authenticity_token , form_authenticity_tokenform_authenticity_token form_authenticity_token form_authenticity_token form_authenticity_token %>
    내용:<textarea type="text" name="guest_content">   </textarea><br>
    
    <br><input type="submit" value="edit"></input>
    </form>

app/views/liverpool/guestbook_new.html.erb
    <form action='/liverpool/guest_create/<%=@guest.id%>' method='post'>
        <%= <%= hidden_field_tag hidden_field_tag hidden_field_tag :authenticity_token authenticity_token authenticity_token authenticity_token , form_authenticity_tokenform_authenticity_token form_authenticity_token form_authenticity_token form_authenticity_token %>
    내용:<textarea type="text" name="guest_content">   </textarea><br>
    
    <br><input type="submit" value="submit"></input>
    </form>
    

    
</form>

    

app/views/liverpool/index.html.erb
<html>
    <head>
        
        <title>Liverpool FC</title>
        
    </head>
    <body>
        <header>
            <h1> Welcome to Liverpool FC </h1>
            <h3> where your dreams come true </h3>
        </header>
        
        <sidebar>
            <ul>
            <li><a href="http://www.liverpoolfc.com/welcome-to-liverpool-fc">Liverpool FC Official Homepage </a></li><br>
            <li><a href="https://korea.store.liverpoolfc.com/?lang=kr&utm_source=lfcuk&utm_medium=redirect&utm_campaign=ip">Liverpool FC Online Store Korea </a></li><br>
            <li><a href="https://www.facebook.com/SouthKoreaLFC/">Liverpool FC Facebook Korea </a></li><br>
            </ul>
        </sidebar>
        
        <main>
            
            <middle>
            <img class="picture1" src="/assets/champions_league_winning.jpg"/>
           
            <h2>-Player List-</Player></h2>
                 <table>
                <tr>
                    <th>Name </th>
                    <th>Year of Birth </th> 
                    <th>Height(cm) </th>
                    <th>Weight(kg) </th>
                    <th>Position </th>
                    <th>         </th>
                </tr>
                <%@lists.each do |list|%>
                <tr>
                    <th><%=list.name%></th>
                    <th><%=list.year_birth%></th>
                    <th><%=list.height%></th>
                    <th><%=list.weight%></th>
                    <th><%=list.position%></th>
                    <th><div class="function"><a href='/liverpool/destroy/<%=list.id%>'><button onclick="myFunction1()">Delete</button></a>
                    
                    
                    <!--<%= link_to '수정', liverpool_edit_path(list_id: list.id) %>-->
                    
                    <!--<%= link_to '수정', {controller: :liverpool, action: :edit, list_id: list.id} %>-->
                    <!--id가 아니라 list_id로 해줘야함-->
  
                    <!--<%= link_to '수정', "/liverpool/edit/#{list.id}/" %>-->
                    <a href='/liverpool/edit/<%=list.id%>'><button onclick="myFunction2()">Edit</button></a>
                    </div></th>
                </tr>
                <script>
                    function myFunction1() {
                    alert("Delete the post");
                    }
                    function myFunction2() {
                    alert("Go to editing page");
                    }
                </script>
                <%end%>   
            </table>
            
            
            <div class="submit">
                <a href="/liverpool/new"><button onclick="myFunction()">Add Player Profile</button> </a>
                </div><br>
            </middle>
            
            <right>
                <h4>방문자 방명록</h4>
                <h5>자유롭게 써주세요</h5>
                <%@guests.each do |guest|%>
                    <%=guest.content%>
                    <tr>
                    <th><div class="function"><a href='/liverpool/guest_destroy/<%=guest.id%>'><button onclick="myFunction1()">Delete</button></a>
                    <a href='/liverpool/guest_edit/<%=guest.id%>'><button onclick="myFunction2()">Edit</button></a></div></th>
                    <br><br>
                <%end%>
                
                
                
            </right>


        </main>
        <footer>
           <h2>You'll Never Walk Alone</h2>
           <img class="picture2" src="/assets/logo.jpg"/>
           <!--<audio src="https://www.youtube.com/watch?v=a9sFd3Ennhs" autoplay controls loop>-->
           <!--   <p>Your browser does not support HTML5 audio playback</p>-->
           <!-- </audio>-->

<!--</audio>-->
        </footer>
    </body>
    
    
    <%= image_tag "stand.jpg", class:"picture1" %>
    
</html>
    

app/views/liverpool/new.html.erb
<p>Add Player Profile</p>


<%= form_for @list, url: liverpool_create_path do |x| %>
    Name: <%= x.text_field :name%><br>
    year_birth:<%= x.text_field :year_birth %><br>
    height :<%= x.text_field :height%><br>
    weight: <%= x.text_field :weight %><br>
    position: <%= x.text_field :position%><br>
    
    <%= x.submit %>

<%end%>




<!--<form action="/liverpool/create" method="post">-->
<!--    Name: <input type="text" name="input_name"></input><br>-->
<!--    Year of Birth: <input type="text" name="input_year_birth"></input><br>-->
<!--    Height: <input type="text" name="input_height"></input><br>-->
<!--    Weight: <input type="text" name="input_weight"></input><br>-->
<!--    Position: <input type="text" name="input_position"></input><br><br>-->
<!--    <input type="submit" value="submit"></input>-->
    
<!--</form>-->